version: "3.8"
services:
  local:
    tty: true
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        repo: "./quartz"
  
  remote:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
      args:
        repo: "https://github.com/ChenghaoMou/quartz"
