services:
  generate:
    platform: linux/arm64/v8
    environment:
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
    tmpfs:
      - /tmp
    build:
      dockerfile: Dockerfile
    volumes:
      - ./templates:/app/templates
      - ./intermediate/highlights/Matter:/app/highlights/Matter
      - ./intermediate/highlights/Readwise:/app/highlights/Readwise
      - ./intermediate/highlights/Zotero:/app/highlights/Zotero
      - ./intermediate/notes:/app/notes
      - ./intermediate/posts:/app/posts
      - ./intermediate/statics:/app/statics
      - ./intermediate/output:/output
      - ./intermediate/index.md:/app/index.md
      - ./intermediate/index.yaml:/app/index.yaml