<footer class="items-center justify-center text-center text-gray-800">
  <bind tag="iconClass">w-6 h-6 hover:text-${theme}-700</bind>
  <div class="flex items-center justify-center mt-2 mb-8 space-x-4">
  <div>
    <a href="${ema:homeUrl}" title="Go to Home page">
      Home
    </a>
  </div>
  <div>
    <a href="${ema:indexUrl}" title="View Index">
      Index
    </a>
  </div>
  <div>
    <a href="${ema:tagIndexUrl}" title="View tags">
      Tags
    </a>
  </div>
  <div>
    <a href="https://github.com/ChenghaoMou/chenghaomou.github.io" title="View Source">
      Source
    </a>
  </div>
  </div>
  <div>
    Generated by
    <a href="https://emanote.srid.ca" target="_blank" title="Generated by Emanote ${ema:version}">
      Emanote
    </a>
  </div>
</footer>
