name: "Publish"
on:
  push:
    branches:
      - main
jobs:
  emanote:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build emanote site 🔧
        run: |
          mkdir output.docker
          docker run \
            -e LANG=C.UTF-8 -e LC_ALL=C.UTF-8 \
            --tmpfs /tmp \
            -v $PWD:/data \
            sridca/emanote \
            sh -c "rm -rf /data/4archives /data/reviews /data/templates/*md /data/boilerplates /data/inbox && emanote -L '/data' gen /data/output.docker --allow-broken-links"
          cp -r output.docker output
      - name: Deploy to gh-pages 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output/