name: "Publish"
on:
  push:
    branches:
      - main
jobs:
  emanote:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build emanote site 🔧
        run: |
          mkdir output.docker
          rm -rf $PWD/4archives
          rm -rf $PWD/boilerplates
          rm -rf $PWD/inbox
          docker run \
            -v $PWD:/data \
            python:3.11-slim \
            sh -c "cd /data && python export/block.py"
          docker run \
            -e LANG=C.UTF-8 -e LC_ALL=C.UTF-8 \
            --tmpfs /tmp \
            -v $PWD:/data \
            sridca/emanote \
            sh -c "emanote -L '/data/intermediate' gen /data/output.docker --allow-broken-links"
          cp -r output.docker output
          cp $PWD/robots.txt output/robots.txt
      - name: Deploy to gh-pages 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output/
